#!/bin/sh

check_files() {
  EXIT=0
  while read -r line; do
    clang-format -style=file -output-replacements-xml $line |
      grep '<replacement ' >/dev/null
    if [ $? -ne 1 ] ; then
      echo clang-format:$line
      EXIT=1
    fi
  done
  exit $EXIT
}

git rev-parse --is-inside-work-tree >/dev/null
if [ $? -ne 0 ] ; then
  exit 1
fi

git ls-files |
  grep '\.[ch]\(pp\)\?$' |
  check_files
